test "SkBee - SecAttributeModifier":

	set {_i} to 1 of stick
	assert movement speed modifier of {_i} is not set with "The item shouldn't have a modifier yet"
	apply attribute modifier to {_i}:
		attribute: movement speed
		slot: feet slot group
		id: "test:test"
		amount: 10
		operation: add_number
	assert movement speed modifier of {_i} is set with "The item should now have a modifier"

	# Test runtime errors
	try:
		apply attribute modifier to {_i}:
			attribute: movement speed
			slot: feet slot group
			id: "test:test @#$@#$"
			amount: 10
			operation: add_number
	catch:
		assert runtime logs contains "Invalid id: test:test @#$@#$" with "Should catch that error"

	try:
		apply attribute modifier to {_i}:
			attribute: movement speed
			slot: feet slot group
			id: {_empty}
			amount: 10
			operation: add_number
	catch:
		assert runtime logs contains "Invalid id: {_empty} (<none>, as java.lang.String)" with "Should catch that error"

	try:
		apply attribute modifier to {_i}:
			attribute: {_empty}
			slot: feet slot group
			id: "test:test"
			amount: 10
			operation: add_number
	catch:
		assert runtime logs contains "Attribute is missing" with "Should catch that error"
