test "SkBee - ExprNamespacedKeyObjectFrom":
    set {_i} to itemtype from key "minecraft:stone"
    assert {_i} is stone with "Should have gotten stone from key"
    delete {_i}

    set {_i} to itemtype from key "blah:bloop"
    assert {_i} is not set with "Shouldn't have gotten anything from this invalid key"

    set {_e} to entitytype from key "minecraft:sheep"
    assert {_e} is a sheep with "Should have gotten a sheep from key"
    delete {_e}

    set {_e} to entitytype from key "minecraft:happy_freaking_horsey"
    assert {_i} is not set with "Shouldn't have gotten anything from this ridiculous key"

    set {_b} to biome from key "minecraft:badlands"
    assert {_b} is badlands with "Should have gotten badlands from key"
    delete {_b}

    set {_b} to biome from key "holy_moly:quacamole"
    assert {_b} is not set with "Ok, that's just silly, come on man"
