main: com.shanebeestudios.skbee.SkBee
name: SkBee
version: '@version@'
description: "A simple Skript addon to help customize your server to the fullest."
api-version: '1.21.4'
author: ShaneBee
website: https://github.com/ShaneBeee/SkBee
folia-supported: true

dependencies:
  server:
    Skript:
      load: BEFORE
      required: true
    SkQuery:
      load: AFTER
      required: false
