main: com.shanebeestudios.skbee.SkBee
name: SkBee
version: '${project.version}'
description: "A simple Skript addon to help customize your server to the fullest."
api-version: '1.13'
author: ShaneBee
website: https://github.com/ShaneBeee/SkBee
softdepend:
  - Skript
  - FastAsyncWorldEdit
  - skript-variable-dump
  - BlueMap
loadbefore:
  - SkQuery
libraries:
  - commons-io:commons-io:2.11.0
  - org.apache.commons:commons-text:1.10.0
commands:
  skbee:
    description: Main SkBee command
    permission: skbee.command
