main: com.shanebeestudios.skbee.SkBee
name: SkBee
version: '@version@'
description: "A simple Skript addon to help customize your server to the fullest."
api-version: '1.20.6'
author: ShaneBee
website: https://github.com/ShaneBeee/SkBee
folia-supported: true

depend:
    - Skript
loadbefore:
    - SkQuery
commands:
    skbee:
        description: Main SkBee command
        permission: skbee.command
permissions:
    skbee.admin:
        default: op
        description: Permission to receive error messages
    skbee.command:
        default: op
        description: Permission to use SkBee's main command
