test "item flags of item":
    set {_i} to unbreakable diamond sword of unbreaking 3 with hide enchants item flag
    assert size of (item flags of {_i}) = 1 with "size of item flags should have been 1"
    assert item flags of {_i} contains hide enchants with "item flags of item should have enchanted 'hide_enchants'"

    add hide unbreakable to item flags of {_i}
    assert size of (item flags of {_i}) = 2 with "size of item flags should have been 2"

    remove hide unbreakable and hide enchants from item flags of {_i}
    assert size of (item flags of {_i}) = 0 with "size of item flags should have been 0"
