test "SkBee - BlockData stuff":
    set {_l} to location(1,1,1)
    set block at {_l} to oak_stairs[waterlogged=true]

    assert blockdata tag "waterlogged" of block at {_l} = true with "blockdata tag ""waterlogged"" should be true"
    set blockdata tag "waterlogged" of block at {_l} to false
    assert blockdata tag "waterlogged" of block at {_l} = false with "blockdata tag ""waterlogged"" should be false"

    set {_data} to oak_stairs[waterlogged=true]

    assert blockdata tag "waterlogged" of {_data} = true with "BlockData tag ""waterlogged"" should be true"
    set blockdata tag "waterlogged" of {_data} to false
    assert blockdata tag "waterlogged" of {_data} = false with "BlockData tag ""waterlogged"" should be false"

    # NOTE: Minecraft MAY change these at any time but I feel like we're safe for a while
    assert size of blockdata tags of oak_stairs[] = 4 with "There should be 4 blockdata tags for oak_stairs"
    assert size of blockdata tags of stone = 0 with "There should be 0 blockdata tags for stone"
