test "SkBee - chunk stuff":

    # Test that these syntaxes don't cause errors
    set {_l} to location(500,100,500)

    load chunk at {_l} with ticket
    assert chunk at {_l} is loaded with "Chunk at location should be loaded"

    unload chunk at {_l}
    wait 5 ticks # Do Skript tests even support waits?!?!?
    assert chunk at {_l} is not loaded with "Chunk at location should have unloaded"
