test "SkBee - Damage Source":
    spawn a sheep at event-location:
        set {_e} to entity
        set {sheep} to true
    spawn a zombie at event-location:
        set {_z} to entity
    set {_source} to damage source of minecraft:cramming directly by {_z}
    assert {_source} is set with "The new damage source should be set"
    damage {_e} by 2 with {_source}

    delete entity within {_e}
    delete entity within {_z}

on damage of sheep:
    if {sheep} is set:
        delete {sheep}
        set {_source} to the damage source
        assert {_source} is set with "The damage source should be set"
        assert damage type of {_source} is minecraft:cramming with "The damage type should be cramming"
        assert causing entity of {_source} is not set with "The causing entity should not be set"
        assert direct entity of {_source} is set with "The direct entity should be set"
        # Skript divides damage by 2
        assert final damage is 1 with "Damage amount should be 1"
