function testSwitch(i: number) :: string:
    return switch return {_i}:
        case 1 -> "i am one"
        case 2 -> "i am two"
        default -> "i am default"

function testSwitchAgain(i: number) :: string:
    return switch return {_i}:
        case 1:
            return "i am one"
        case 2:
            return "i am two"
        default:
            return "i am default"

function testItem(b: itemtype) :: string:
    return switch return {_b}:
        case stone, dirt, grass block -> "natural blocks"
        case gravel, sand -> "mushy blocks"
        default -> "default blocks"

test "SkBee - Switch and Case":
    set {_i} to 2
    switch {_i}:
        case 1:
            set {_test} to 1
        case 2:
            set {_test} to 2
        case 3:
            set {_test} to 3
    assert {_test} = 2 with "Case 2 should have run"

    set {_i} to diamond sword named "BOB"
    switch type of {_i}:
        case diamond:
            assert {_i} is a diamond with "This should be failing"
            set {_test} to 1
        case iron ingot:
            assert {_i} is an iron ingot with "This should be failing"
            set {_test} to 2
        case diamond sword:
            assert {_i} is a diamond sword with "This should pass"
            set {_test} to 3
    assert {_test} = 3 with "The 3rd case should have run"

    parse:
        switch event-block:
            case plains:
                set {_i} to 1
            case 1:
                set {_i} to 1
    assert parse logs contains "Can't compare a block with a biome" with "The comparisons should have failed"
    assert parse logs contains "Can't compare a block with an integer" with "The comparisons should have failed"

    # Test Functions
    assert testSwitch(1) = "i am one" with "This should be 'i am one'"
    assert testSwitch(2) = "i am two" with "This should be 'i am two'"
    assert testSwitch(3) = "i am default" with "This should be 'i am default'"
    assert testSwitchAgain(1) = "i am one" with "This should be 'i am one'"
    assert testSwitchAgain(2) = "i am two" with "This should be 'i am two'"
    assert testSwitchAgain(3) = "i am default" with "This should be 'i am default'"
    assert testItem(dirt) = "natural blocks" with "This should be 'natural blocks'"
    assert testItem(stone) = "natural blocks" with "This should be 'natural blocks'"
    assert testItem(grass block) = "natural blocks" with "This should be 'natural blocks'"
    assert testItem(gravel) = "mushy blocks" with "This should be 'mushy blocks'"
    assert testItem(sand) = "mushy blocks" with "This should be 'mushy blocks'"
    assert testItem(pink wool) = "default blocks" with "This should be 'default blocks'"
