test "SkBee - Text/EffComponentReplace":

	set {_component} to text component from "Mom! Look! I'm on television!"
	component replace "Mom" with "Dad" in {_component}
	assert {_component} is "Dad! Look! I'm on television!"

	set {_component} to text component from "Mom! Mom! Look at me!"
	component replace first "Mom" in {_component} with "Dad"
	assert {_component} is "Dad! Mom! Look at me!"

	set {_component} to text component from "Hello! Hi! Howdy! Sup!"
	component regex replace "(Hello|Howdy)" with "Salut" in {_component}
	component regex replace "(Hi|Sup)" with "Hola" in {_component}
	assert {_component} is "Salut! Hola! Salut! Hola!"
