main: com.shanebeestudios.skbee.SkBee
name: SkBee
version: '1.12.3'
description: "A simple Skript addon to help customize your server to the fullest."
api-version: '1.13'
author: ShaneBee
website: https://github.com/ShaneBeee/SkBee
softdepend:
  - Skript
  - FastAsyncWorldEdit
  - skript-variable-dump
loadbefore:
  - SkQuery
